- name: "set up {{component}} server"
  hosts: "{{component}}"
  become: yes
  roles:
  - "{{component}}"
  vars:
    MONGODB_HOST: mongodb.nikitha.fun
    REDIS_HOST: redis.nikitha.fun
    CATALOGUE_HOST: catalogue.nikitha.fun 
    USER_HOST: user.nikitha.fun
    FRONTEND_HOST: frontend.nikitha.fun
